config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'bookmarks#index'

  resources :bookmarks, except: [:show]
  resources :search, only: [:index]
  get 'tags/:tag_name', to: 'bookmarks#index', as: :tags
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  belongs_to :site
  has_and_belongs_to_many :tags

  validates :title, presence: true
  validates :url, presence: true

  before_validation :set_parent_site
  around_destroy :destroy_orphaned_parent

  scope :tagged_with, ->(tag_name) { joins(:tags).where('tags.name=?', tag_name) }

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    tags.map(&:name).join(', ')
  end

  private

  def set_parent_site
    url_base = URI.parse(url).host
    if url_base.present?
      url_base = "http://#{url_base}" unless url_base.start_with? 'http'
      self.site = Site.find_or_create_by(url: url_base)
    end
  end

  def destroy_orphaned_parent
    parent = site
    yield # executes a DELETE database statement
    parent.destroy if parent.bookmarks.empty?
  end
end

app/models/site.rb
# frozen_string_literal: true

class Site < ApplicationRecord
  has_many :bookmarks, dependent: :destroy

  validates :url, uniqueness: true
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_and_belongs_to_many :bookmarks

  scope :used, -> { Tag.joins(:bookmarks).group('tags.id').having('count(bookmarks.id) > 0') }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
# frozen_string_literal: true

class BookmarksController < ApplicationController
  def index
    @sites = Site.all
  end

  def create
    @bookmark = Bookmark.create permitted_params
    if @bookmark.valid?
      flash[:notice] = 'Bookmark was successfully created.'
      redirect_to bookmarks_path
    else
      flash[:error] = 'There were errors. Please fix them below.'
      render 'new'
    end
  end

  def new
    @bookmark = Bookmark.new
  end

  def edit
    @bookmark = Bookmark.find params[:id]
  end

  def update
    @bookmark = Bookmark.find params[:id]
    if @bookmark.update permitted_params
      flash[:notice] = 'Bookmark was successfully updated.'
      redirect_to bookmarks_path
    else
      flash[:error] = 'There were errors. Please fix them below.'
      render 'edit'
    end
  end

  def destroy
    bookmark = Bookmark.find params[:id]
    bookmark.destroy

    flash[:notice] = 'Bookmark was successfully deleted.'
    redirect_to bookmarks_path
  end

  private

  def permitted_params
    params.require(:bookmark).permit(:id, :title, :url, :shortening, :all_tags)
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def index
    @bookmarks = if params[:query].present?
                   Bookmark
                     .where('LOWER(title) like LOWER(:search) or
                                          LOWER(url) like LOWER(:search) or
                                          LOWER(shortening) like LOWER(:search) or id in
                                           (select bookmark_id from "bookmarks_tags" as bt, "tags" as t
                                             where t.id = bt.tag_id and LOWER(t.name) like LOWER(:search)
                                           )',
                            search: "%#{params[:query]}%")
                 else
                   []
                 end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def screenshot_image_tag(url)
    image_tag "http://api.page2images.com/directlink?p2i_url=#{url}&p2i_key=#{ENV['PAGE2IMAGES_API']}&p2i_device=0&p2i_size=150x150&p2i_screen=1280x800" # rubocop:disable Metrics/LineLength
  end

  def nav_link(link_text = nil, link_path, &block)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, class: class_name) do
      if block_given?
        link_to link_path, &block
      else
        link_to link_text, link_path
      end
    end
  end
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper
end

app/views/bookmarks/_bookmark.html.slim
.bookmark-box
  = link_to bookmark.url, target: '_blank' do
    = screenshot_image_tag bookmark.url
    .description
      = bookmark.title
  .tags
    - bookmark.tags.each do |tag|
      span.label.label-default= tag.name
  .actions
    = link_to edit_bookmark_path(bookmark), class: 'btn btn-primary btn-xs' do
      i.glyphicon.glyphicon-pencil
      = link_to bookmark, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do
        i.glyphicon.glyphicon-remove

app/views/bookmarks/_form.html.slim
.row
  .col-sm-6
    = simple_form_for @bookmark do |f|
      = f.input :title
      = f.input :shortening
      = f.input :url, type: :url
      = f.input :all_tags
      p.small Use comma "," for separating tags.
      .clearfix
        = f.button :submit, class: 'btn btn-success pull-right'
        = link_to 'Cancel', bookmarks_path, class: 'btn btn-default'

app/views/bookmarks/edit.html.slim
h1 Edit Bookmark
= render 'form'

app/views/bookmarks/index.html.slim
#accordion.panel-group aria-multiselectable='true' role='tablist'
  - if @sites.blank?
    .panel.panel-default
      .panel-heading
        h4.panel-title No bookmarks yet.
        = link_to 'Why not adding one?', new_bookmark_path

  - @sites.each_with_index do |site, index|
    .panel.panel-default
      .panel-heading role='tab' id="site_header_#{index}"
        h4.panel-title
          a aria-controls='collapseOne' aria-expanded='true' data-parent='#accordion' data-toggle='collapse' href="#site_content_#{index}" role='button'
            = site.url
      .panel-collapse.collapse aria-labelledby="site_header_#{index}" role='tabpanel' id="site_content_#{index}" class="#{'in' if index == 0}"
        .panel-body
          - if params[:tag_name].present?
            - site.bookmarks.tagged_with(params[:tag_name]).each do |bookmark|
              = render bookmark
          - else
            - site.bookmarks.each do |bookmark|
              = render bookmark

app/views/bookmarks/new.html.slim
h1 New Bookmark
= render 'form'

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded='false' data-target='#bs-example-navbar-collapse-1' data-toggle='collapse' type='button'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href='/'  Bookmarks
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        = nav_link 'New', new_bookmark_path

        li.dropdown
          a.dropdown-toggle aria-expanded='false' aria-haspopup='true' data-toggle='dropdown' href='#' role='button'
            | Filter by Tag
            span.caret
          ul.dropdown-menu
            - Tag.used.each do |tag|
              = nav_link tags_path(tag.name) do
                = tag.name
                span.badge.pull-right= tag.bookmarks.count



      =form_tag '/search', method: 'get', class: 'navbar-form navbar-right'
        .input-group
          = text_field_tag :query, params[:query], class: 'form-control', placeholder: 'Search'
          .input-group-btn
            button.btn.btn-default id='search-submit' type='submit'
              i.glyphicon.glyphicon-search

app/views/layouts/application.html.slim
doctype html
html
  head
    title Bookmarking
    = csrf_meta_tags
    meta content='initial-scale=1, width=device-width' name='viewport' /
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
  body
    = render 'layouts/navbar'
    .container
      - if flash[:notice]
        .alert.alert-success
          button.close aria-label='Close' data-dismiss='alert' type='button'
            span aria-hidden='true'  &times;
          = flash[:notice]

      - if flash[:error]
        .alert.alert-warning
          button.close aria-label='Close' data-dismiss='alert' type='button'
            span aria-hidden='true'  &times;
          = flash[:error]

      = yield

app/views/search/index.html.slim
h1= "Search results for \"#{params[:query]}\""
.list-group.search-results
  - if @bookmarks.blank?
    .list-group-item No results.
  - @bookmarks.each do |bookmark|
    = link_to bookmark.url, target: '_blank', class: 'list-group-item' do
      = "#{bookmark.title} (#{bookmark.url})"
      .tags
        - bookmark.tags.each do |tag|
          span.label.label-default= tag.name